### ISSUE TITLE
Figure out best way to handle shipping to both English- and German-speaking users

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/gecko-dev#12]
Per the revised [PHD](https://docs.google.com/document/d/1emT5bdFQoMh5Zl0bLZS5fHKWKhXRpLrptDesKdfQYCw/edit?usp=sharing), the target users are:
* en-US + US geo (sample 1) and de-DE + Germany geo (sample 2)

This might be similar to the [Tracking Protection Messaging study](https://bugzilla.mozilla.org/show_bug.cgi?id=1433473#c14), where there were two different Normandy recipes. In this case, perhaps one recipe targets US and one recipe targets DE?

Related issue: #9 .

@gregglind, @MattGrimes, what would you recommend?

**Comment by gregglind** [comment]
Two recipes :).

Easier to adjust the percentages that way.
