### ISSUE TITLE
Record "login form" success/failure for a small set sites via hard coding per site

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/gecko-dev#19]
### Background
The login form probe seeks to measure form load, submit, success and failure. Success and failure are very difficult to know from the browser.

Why? From a protocol level, the user submits a form, and the browser directs them to a page. The page shows different content depending on success or failure. To reliably know which, we would have to be familiar with each site’s login flow. There is currently an open [bug]( https://bugzilla.mozilla.org/show_bug.cgi?id=558178) for this as well.

### Workaround
The main heuristic is: if there are no password fields on the page loaded after the form is submitted, then the login would be considered “successful”. This heuristic happens to work for both Google and Facebook currently.

Per osmose (paraphrase):
> Basically after the form is submitted, I could wait for the page to load, get the document object, and use querySelector to find the password field

Per rhelmer:
> I think there's a way to add an observer for certain elements coming out of the html parser, but I think it's probably a fair bit of work just to investigate

### Needinfo
Need the shortlist of sites to hard code from stakeholders. (requested in Weekly update e-mail 05/16/18)

**Comment by SuYoungHong** [comment]
as per Romain's comments in the email thread, we can ignore `failure` and `success` events for `login form` for now and just record `load` and `submit` for this probe.

**Comment by biancadanforth** [comment]
Closing per "Savant Weekly Update" e-mail thread with decision by Romain on 05/17/18 to omit login form `success`/`failure` probes.
