### ISSUE TITLE
Add pwmgr_use and pwmgr probes

### ISSUE THREAD

**Issue by biancadanforth** [biancadanforth/gecko-dev#20]
Suggestions per MattN: try adding the `recordEvent` at the same location as where the code described is found and verify that it works as expected.

**Notes about flow_id using tab identifier `linkedPanel`:**
For a given session, that string remains constant, even if the tab is moved to a different index within the same window, for different windows, the string will change. For closing and reopening the window the string will change (like with session restore) 

### `pwmgr_use`
* `save`: Client saves a password to the Password Manager
  * PWMGR_PROMPT_REMEMBER_ACTION (HISTOGRAM: Action taken by user through prompt for creating a login. (0=Prompt displayed [always recorded], 1=Add login, 2=Don't save now, 3=Never save)
  * PWMGR_PROMPT_UPDATE_ACTION (HISTOGRAM: Action taken by user through prompt for modifying a login. (0=Prompt displayed [always recorded], 1=Update login)).
  * `nsLoginManagerPrompter.js` broadcasts an observer notification `passwordmgr-prompt-change` and `passwordmgr-prompt-save`. The former is that they were prompted, not that they actually changed the password. The latter observer notification means they prompted user for what they think is a new password.
* `use`: Client uses a password from the Password Manager
  * This can happen by the user selecting a dropdown option on a login form or by right clicking a login form input element and selecting "Fill Login" from the context menu.
  * > I think you would want to record in the `finally` block at https://dxr.mozilla.org/mozilla-central/rev/1800b8895c08bc0c60302775dc0a4b5ea4deb310/toolkit/components/passwordmgr/LoginManagerContent.jsm#1263
    * Note: Doing this resulted in `recordEvent` being called 3x before I even autofilled the login form. I moved it up to be the [very last line](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr/LoginManagerContent.jsm?q=LoginStats%3ALoginFillSuccessful&redirect_type=single#1257) of the `try` clause instead in PR #21 .

### `pwmgr`
* `ask` (aka prompt): Password Manager prompts user to save their password
  * Same as `save` under `pw_manager_use` above.
* `save`: User elects to save their password after being prompted.
  * Same as `save` under `pw_manager_use` above.

@SuYoungHong, I'm having trouble distinguishing the `pw_manager_use` - `save` event and the `pw_manager` - `save` event. Can you help me clarify? Also, for saving, do you want me to distinguish a save prompt/save action from an update prompt/update action?

**Comment by biancadanforth** [comment]
TODO - add TESTPLAN.md updates for this probe:

Verify pw manager probes "save" and "ask" work:
1. Navigate to facebook.com
2. enter in a made-up username and password (remember the username)
3. After you submit the login information, you’ll see a Password Manager panel prompt.
4. Click “Save”.
5. Go into `about:telemetry` for the current ping, and click on “Events” in the side menu.
6. Observe there are two events, pw_manager ask and pw_manager save.
7. Repeat steps 1-3. Then click “Don’t Save”.
8. Go into `about:telemetry` for the current ping, and click on “Events” in the side menu.
9. Observe there is only one event, pw_manager ask.

Verify pw manager probe "use" works:
TODO

**Comment by SuYoungHong** [comment]
@biancadanforth , as per our slack conversation May18th , yes , if possible, please include an `update` option for `pw_manager`, with the distinction between `pw_manager - save` and `pw_manager - update` being that save is saving a brand new pw entry, whereas update is changing an existing one. 

however, it is also fine to lump them together if there are time / code constraints. 

- Su
