### ISSUE TITLE
Rewrite Specs to Conform to Events Telemetry API

### ISSUE THREAD

**Issue by SuYoungHong** [biancadanforth/gecko-dev#23]
Had a very helpful vidyo meeting with sunah and the following points were brought up: 

1) Events telemetry's design is such that `category`, `method`, and `object` are all required fields (non-null). `value` and `extra` can be null. 
2) In terms of grouping a family of events together, that should be done at the `category` level. One thing about `category`, they can be turned 'on' or 'off' (turn category X on), and we might partition by this field in the future. Right now, I've defined things with very 'broad' categories, but it's advised to narrow the categories more specifically, (i.e. 'nav-bookmark' as opposed to 'navigation'). 
3) Other then `category` and the `method` and `object` requirements, events are not really hierarchical. 

These suggestions should deal with some of the issues of how to property group families of events together. 

After reviewing the schema, she recommended switching some of the method and value and object fields, to conform to the API standards. Also, divide up categories into more specific categories. 

To Do: (Su) Rewrite the schema according to her suggestions. 
To Do: (Su) After re-writing, get review of schema from Sunah.

**Comment by SuYoungHong** [comment]
Specs re-written here: 
https://docs.google.com/spreadsheets/d/192unlFYdQ_nc5UVaG79YhY2bp6bV7XZm1G4BW-etOLE/edit#gid=0

under 'redefined schema' page/sheet

sent to group for review

**Comment by biancadanforth** [comment]
Thanks Su for meeting with Sunah and sharing her recommendations.

Prior to this spec re-write, I submitted a patch to lump all the probes we are adding as part of this study under a new `"savant"` category. This was originally recommended to me by chutten, who is our Data Steward reviewer.

**Advantages to a one-category approach**
* We know which probes are associated with the study
* There is only one category of event telemetry to turn on and off (easier for testing/development)
* For the case of the `"search"` probe, which already exists, duplicating it under the `"savant"` category allows me to isolate it from being enabled/disabled by code elsewhere in Firefox.

**Advantages for a multi-category approach**
* For any probes we want to keep after our study (or future studies), making the probes permanent would require less rejiggering of `Events.yaml`; though we'd want to be sure we had very sensible category/method names that followed any existing conventions.

**Proposed spec changes for a one-category approach**
If we were to keep the one study category approach, I would propose we prefix the category strings you have listed in the [revised spec](https://docs.google.com/spreadsheets/d/192unlFYdQ_nc5UVaG79YhY2bp6bV7XZm1G4BW-etOLE/edit#gid=1257575649) with their method names. For example: category `"nav-bookmark"` with a method of `"open"` becomes category `"savant"` with a method of `"nav-bookmark-open"`.

**Get a second opinion before going one way or the other?**
I'd like to get @chutten 's opinion on this, as it affects a [patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1462725) I've been working on this week that I just requested him to review (with the one `"savant"` category). I'm definitely open to changing this, I just want to make sure we go the route that makes the most sense.

**Comment by SuYoungHong** [comment]
@biancadanforth , I see. In that case, I'm okay with using the one-category approach, for this particular experiment. 

The one category schema feels a bit icky for a general release probe, but since this is an experiment, I'm okay with it (as long as it gets fixed to something more generalized if we ever turn on these probes outside of the scope of the experiment). 

But I'm 100% on board switching to the 1 category method (`savant`) using the method you described (concatenating the current events with the action). 

Maybe one suggestion? When we concat the current category and the action, maybe have a reserved delimiter, so we can split when we need to and group by the old category. Not sure how feasible or complicating this is, but it could be nice to have. 

- Su

**Comment by biancadanforth** [comment]
Okay Su and I just vidyo-ed on this, and we agreed to continue upon my current path, which flips the convention of `method` and `objects` around, so that we can keep a single category `savant`. We agreed to put the original category in the `extra` field. Here's an example for the `pw_manager` probe:
* category: "savant", method: "pw_manager", objects: ["use", "save", "update"], value: null, extra: { "event-sub-category": "feature" }

**Comment by biancadanforth** [comment]
Closed per #4 .
